# Generated by Django 3.0.3 on 2020-05-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comodity_Name', models.CharField(choices=[('SA', 'Saffron'), ('PS', 'Pistachio')], max_length=2)),
                ('En_DateTime', models.DateTimeField()),
                ('Fa_DateTime', models.TextField()),
                ('Maturity_Date', models.CharField(choices=[('ES', 'Esfand'), ('DY', 'Dey')], max_length=2)),
                ('AP1', models.IntegerField()),
                ('AP2', models.IntegerField()),
                ('AP3', models.IntegerField()),
                ('BP1', models.IntegerField()),
                ('BP2', models.IntegerField()),
                ('BP3', models.IntegerField()),
                ('LastDay_Settlement', models.FloatField()),
                ('AV1', models.IntegerField()),
                ('AV2', models.IntegerField()),
                ('AV3', models.IntegerField()),
                ('BV1', models.IntegerField()),
                ('BV2', models.IntegerField()),
                ('BV3', models.IntegerField()),
                ('Last_Price', models.IntegerField()),
                ('Volume_Traded', models.IntegerField()),
                ('Open_Interest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option_Symbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol_Name', models.CharField(max_length=20)),
                ('Symbol_Id', models.IntegerField()),
                ('Underlying_Asset', models.CharField(max_length=20)),
                ('Strike', models.IntegerField()),
                ('Exercise_Date', models.DateField()),
                ('Option_Type', models.CharField(choices=[('P', 'Put'), ('C', 'Call')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol_Name', models.CharField(max_length=20)),
                ('Symbol_Id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeExample', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Symbols_Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('DateTime', models.DateTimeField()),
                ('Price', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Value', models.IntegerField()),
                ('Symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.Symbols')),
            ],
        ),
        migrations.CreateModel(
            name='Symbols_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.Symbols')),
            ],
        ),
    ]
